package gemini

import (
	"context"
	"errors"
	"fmt"
	"mcpexample/internal/logger"
	"os"

	"google.golang.org/genai"
)

var log = logger.Log

const ENV_GEMINI_KEY = "GEMINI_KEY"
const MODEL_2_5_PRO = "gemini-2.5-pro"

// prompt sends the user input to the Gemini model
// and returns the response
// Parameters:
//   - userPrompt: The prompt input from the user.
//
// Returns:
//   - string: The response generated by the Gemini model.
//   - error: An error object if an error occurs, otherwise nil.
func prompt(userPrompt string) (string, error) {
	log.Info("Sending prompt to Gemini model", "prompt", userPrompt)

	apiKey, ok := os.LookupEnv(ENV_GEMINI_KEY)
	if !ok {
		return "", errors.New("error: prompt : Gemini API key not found in environment variables")
	}

	return promptWithAPIKey(userPrompt, apiKey, MODEL_2_5_PRO)
}

// promptWithAPIKey sends the user input to the Gemini model
// using the provided API key and returns the response
//
// Parameters:
//   - userPrompt: The prompt input from the user.
//   - apiKey: The Gemini API key for authentication.
//   - llmModel: The name of the LLM model to use.
//
// Returns:
//   - string: The response generated by the Gemini model.
//   - error: An error object if an error occurs, otherwise nil.
func promptWithAPIKey(userPrompt string, apiKey string, llmModel string) (string, error) {

	log.Info("Sending prompt to Gemini model with API key", "prompt", userPrompt, "model", llmModel)

	if apiKey == "" {
		log.Error("API key is missing")
		return "", errors.New("error: promptWithAPIKey : API key is missing")
	}
	ctx := context.Background()

	client, err := genai.NewClient(ctx, &genai.ClientConfig{
		APIKey:  apiKey,
		Backend: genai.BackendGeminiAPI,
	})
	if err != nil {
		return "", fmt.Errorf("error: could not create new gemini client : %v", err)
	}
	result, err := client.Models.GenerateContent(
		ctx,
		llmModel,
		genai.Text(userPrompt),
		nil,
	)
	if err != nil {
		return "", fmt.Errorf("error: failed to generate content with user prompt [%s]: %v", userPrompt, err)
	}
	log.Info("Received response from Gemini model", "response", result.Text())
	return result.Text(), nil
}
